Remove decedent fetus and parent education
HL7/vr-common-library pull request #10
Opened 2023-11-15 16:11 UTC by ptran265

- removed PatientDecedentFetus and ParentEducationLevel from VRCL
- another PR coming to add PatientDecedentFetus to BFDR

2023-11-15 16:16 UTC, saulakravitz requested changes

2023-11-15 16:16 UTC, saulakravitz commented on input/fsh/instances/patient-decedent-fetus-not-named.fsh.save
Shouldn't this example move to BFDR?

2023-11-15 16:20 UTC, rpassas commented
Would be good to track these changes in the changelog

2023-11-15 17:06 UTC, ptran265 commented on input/fsh/instances/patient-decedent-fetus-not-named.fsh.save
I deleted it from VRCL and added it to BFDR (just made pull request in BFDR)

2023-11-17 15:50 UTC, saulakravitz approved these changes

2023-11-17 15:52 UTC, merged