Form mapping edit
HL7/vr-common-library pull request #45
Opened 2023-12-28 03:44 UTC by rpassas

### Summary

Forms mapping tables are hidden by default on page intros.

2023-12-28 15:43 UTC, ptran265 requested changes

2023-12-28 15:43 UTC, ptran265 commented on input/pagecontent/StructureDefinition-Extension-partial-date-time-vr-intro.md
this somehow mistakenly got added

2023-12-28 15:43 UTC, ptran265 commented on input/pagecontent/StructureDefinition-Extension-partial-date-vr-intro.md
same here

2023-12-28 17:23 UTC, saulakravitz reviewed
RelatedPerson - Father Vital Records missing IJE and Forms mapping.

2023-12-29 20:13 UTC, saulakravitz approved these changes

2023-12-29 20:20 UTC, merged